### ISSUE TITLE
Could not resolve com.adobe.marketing.mobile:assurance:2.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by Girish-GAP** [adobe/aepsdk-react-native#500]
### Prerequisites

- [x] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-react-native/security/policy).
- [x] I have searched in this repository's issues to see if it has already been reported.
- [x] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

I'm encountering an issue when trying to build my Android app. The build fails with the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportMyAppRelease'.
> Could not resolve all task dependencies for configuration ':app:MyAppReleaseRuntimeClasspath'.
   > Could not resolve com.adobe.marketing.mobile:edgeidentity:2.+.
     Required by:
         project :app > project :adobe_react-native-aepedgeidentity
      > Could not resolve com.adobe.marketing.mobile:edgeidentity:2.0.1-SNAPSHOT.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/edgeidentity/2.0.1-SNAPSHOT/edgeidentity-2.0.1-SNAPSHOT.pom'.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/edgeidentity/2.0.1-SNAPSHOT/edgeidentity-2.0.1-SNAPSHOT.pom'.
               > Read timed out

### Environment

- React Native version: 0.73.x
- @adobe/react-native-aepassurance version: ^7.0.0
- Android Gradle Plugin: 8.x
- Gradle: 8.x
- Build Type: `Release`

I verified this by running:

```bash
curl -I https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/assurance/2.0.0-SNAPSHOT/maven-metadata.xml

This returns 404, confirming the version does not exist.



### Steps to reproduce

@adobe/react-native-aepassurance@^7.0.0 in a React Native app dependencies

Build with: ./gradlew app:assembleRelease

Observe failure due to missing 2.0.0-SNAPSHOT

### Current behavior

_No response_

### Expected behavior

_No response_

### Anything else?

_No response_

**Comment by vivektkclt** [comment]
same issue in latest version of Adobe plugins tried with 7.0.0

         project :adobe_react-native-aepassurance
> Repository maven is disabled due to earlier error below:
> Could not resolve com.adobe.marketing.mobile:sdk-bom:3.1.0-SNAPSHOT.
> Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/sdk-bom/3.1.0-SNAPSHOT/maven-metadata.xml.
> Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/sdk-bom/3.1.0-SNAPSHOT/maven-metadata.xml'.
> Read timed out
> There is 1 more failure with an identical cause.

**Comment by vivektkclt** [comment]
> ### Prerequisites
> * [x]  This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-react-native/security/policy).[x]  I have searched in this repository's issues to see if it has already been reported.[x]  I have updated to the latest released version of the SDK and the issue still persists.
> 
> ### Bug summary
> I'm encountering an issue when trying to build my Android app. The build fails with the following error:
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not determine the dependencies of task ':app:lintVitalReportMyAppRelease'.
> 
> > Could not resolve all task dependencies for configuration ':app:MyAppReleaseRuntimeClasspath'.
> > Could not resolve com.adobe.marketing.mobile:edgeidentity:2.+.
> > Required by:
> > project :app > project :adobe_react-native-aepedgeidentity
> > > Could not resolve com.adobe.marketing.mobile:edgeidentity:2.0.1-SNAPSHOT.
> > > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/edgeidentity/2.0.1-SNAPSHOT/edgeidentity-2.0.1-SNAPSHOT.pom'.
> > > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/edgeidentity/2.0.1-SNAPSHOT/edgeidentity-2.0.1-SNAPSHOT.pom'.
> > > Read timed out
> 
> ### Environment
> * React Native version: 0.73.x
> * @adobe/react-native-aepassurance version: ^7.0.0
> * Android Gradle Plugin: 8.x
> * Gradle: 8.x
> * Build Type: `Release`
> 
> I verified this by running:
> 
> curl -I https://oss.sonatype.org/content/repositories/snapshots/com/adobe/marketing/mobile/assurance/2.0.0-SNAPSHOT/maven-metadata.xml
> 
> This returns 404, confirming the version does not exist.
> 
> 
> 
> ### Steps to reproduce
> 
> @adobe/react-native-aepassurance@^7.0.0 in a React Native app dependencies
> 
> Build with: ./gradlew app:assembleRelease
> 
> Observe failure due to missing 2.0.0-SNAPSHOT
> 
> ### Current behavior
> 
> _No response_
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Anything else?
> 
> _No response_

**Comment by Girish-Official-CBT** [comment]
✅ Update: The issue is resolved now. It seems the snapshot dependency became available again or there was a temporary connectivity issue with the snapshot repo.

**Comment by vivektkclt** [comment]
Sure! Here's a rephrased version suitable for posting as a question on Adobe's GitHub issues:

---

**Is there a way to override the following dependency to use a specific stable version instead of a dynamic one?**

```groovy
implementation platform("com.adobe.marketing.mobile:sdk-bom:3.+")
```

We're currently experiencing build issues because this dynamic version (`3.+`) resolves to different snapshot versions, which are unstable or sometimes unavailable. We'd like to lock it to a specific stable version, possibly through our CI pipeline or some form of override. Any guidance on how to achieve this would be appreciated.

**Comment by Girish-GAP** [comment]
🔁 Update: The issue has reappeared intermittently.

It seems the `SNAPSHOT` dependency for `@adobe/react-native-aepassurance` or related modules is not consistently available on the Sonatype snapshot repository. This is affecting our production/release builds, even though it works occasionally.

Could you please:

1. Publish a stabl version if possible?
2. Recommend a workaround to avoid build-time failures due to snapshot dependency unavailability?

**Comment by true-hamid** [comment]
> I have tried different approaches to reproduce the issue, but have been unsuccessful. The app was still built correctly, even though I saw a similar warning: `Failed to resolve: com.adobe.marketing.mobile:assurance`
> 
> I also uploaded my test app to the GitHub repository: https://github.com/yangyansong-adbe/react-native-android-build-issue, Please download and build it locally and see if the test app can be built correctly.
> 
> What happened to the Android app build process:
> 
> * Gradle (build tool) tried to download the adobe sdk from `oss.sonatype.ort/… ` but this artifact repository is not stable as mentioned above. So Gradle prints the above `Failed to resolve error`.
> * Gradle tried to download the sdk from other repositories and find the sdk build from "[http://repo.maven.apache.org/maven](http://repo.maven.apache.org/mavene/)"
> * Finally, the app is built correctly with the sdk downloaded from `repo.mven.apache.org`.
> 
> The screenshot below shows the above behavior:
> 
> <img alt="Image" width="1161" height="330" src="https://private-user-images.githubusercontent.com/47394585/473616737-caee7dee-2ed6-4744-9000-510d7357dda4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQxMTE3MTAsIm5iZiI6MTc1NDExMTQxMCwicGF0aCI6Ii80NzM5NDU4NS80NzM2MTY3MzctY2FlZTdkZWUtMmVkNi00NzQ0LTkwMDAtNTEwZDczNTdkZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAyVDA1MTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMzU0ZTI3N2QyYjY4OTkzN2ZiY2UyOTE2ODFmYmFiNGQ1YmI2M2FmNWFlZjQzODU2MDI1YTA2Y2MxMGVjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-dQENtxrYZY-L6uaf0c6nYS7Jta86zVGCHNp4kDW9_E">
> So, one thing we can confirm is that if their Android project setup includes the correct repo url.
> 
> Here is the code that prints all of the repo urls that were added to the Android project:
> 
> ```
> repositories.each { repo ->
>     println "Repository Name: ${repo.name}"
>     println "Repository URL: ${repo.url}"
>     println "Repository Class: ${repo.class.simpleName}"
>     println "---"
> } 
> ```
> 
> Here is an example of where I added the above code to the test app: https://github.com/yangyansong-adbe/react-native-android-build-issue/blob/main/AwesomeProject/android/build.gradle#L23-L28
> 
> And, it's output:
> 
> ```
> > Configure project :
> Repository Name: maven
> Repository URL: https://oss.sonatype.org/content/repositories/snapshots/
> Repository Class: DefaultMavenArtifactRepository_Decorated
> ---
> Repository Name: MavenRepo
> Repository URL: https://repo.maven.apache.org/maven2/
> Repository Class: DefaultMavenArtifactRepository_Decorated
> ---
> Repository Name: maven2
> Repository URL: file:/Users/yy/GIT/Github/react-native-android-build-issue/AwesomeProject/node_modules/jsc-android/dist/
> Repository Class: DefaultMavenArtifactRepository_Decorated
> ---
> Repository Name: Google
> Repository URL: https://dl.google.com/dl/android/maven2/
> Repository Class: DefaultMavenArtifactRepository_Decorated
> ---
> Repository Name: maven3
> Repository URL: https://www.jitpack.io
> Repository Class: DefaultMavenArtifactRepository_Decorated
> ---
> ```

@yangyansong-adbe the issues is that adobe sdks try to download from https://oss.sonatype.org/content/repositories/snapshots/ which is intermittently unavailable, and we be completely shut down at any point now as their end of life was on 30th June 2025. Please check https://central.sonatype.org/pages/ossrh-eol/.

**Comment by true-hamid** [comment]
@yangyansong-adbe I have "repo.maven.apache.org/maven2/" (mavenCentral()) configured but I am still facing this issue. 

<img width="160" height="100" alt="Image" src="https://github.com/user-attachments/assets/3ef501aa-be22-4a5f-980a-da87fa8f6f7d" />

**Comment by vivektkclt** [comment]
We're still facing this issue, and it's currently a **blocker for the entire app build pipeline**.

### ✅ What we've tried so far:

* Verified this is related to instability on `https://oss.sonatype.org`.
* Attempted to mirror `maven-metadata.xml` and related artifacts locally.
* Tried redirecting Maven/Gradle to use a local repository via `repositories { maven { url uri('./local-repo') } }`.
* Looked into patching or overriding the Adobe plugin behavior — but repository resolution seems to be internally controlled and not configurable.

### 🔴 Current Status:

Despite setting up local mirrors, the plugin (or the underlying build process) still attempts to resolve dependencies via `oss.sonatype.org`, which remains unstable.

This is causing:

* **Failed builds across CI/CD pipelines**
* **Complete disruption in app release process**

### 🙏 Request:

Please consider either:

1. Providing a way to override or configure the repository endpoint in the plugin.
2. Publishing a stable (non-snapshot) release version of the affected packages.
3. Offering a workaround that doesn't rely on Sonatype until it stabilizes.

Let us know if there's a short-term patch or if we can contribute a configurable solution via PR.

**Comment by yangyansong-adbe** [comment]
@true-hamid, could you check if your local machine can access this Maven repository URL(https://repo.maven.apache.org/maven2/com/adobe/marketing/mobile/) and see the underlying builds as in the screenshot below?

<img width="623" height="595" alt="Image" src="https://github.com/user-attachments/assets/9140decf-7d64-4604-b2ab-9abaef61dc46" />

**Comment by true-hamid** [comment]
I can access the url @yangyansong-adbe, but it seems as @vivektkclt  mentioned:  
> the plugin (or the underlying build process) still attempts to resolve dependencies via oss.sonatype.org, which remains unstable.

<img width="839" height="921" alt="Image" src="https://github.com/user-attachments/assets/ca4cff0a-21b3-4876-968c-d5df030a8f50" />

**Comment by vivektkclt** [comment]
@yangyansong-adbe 

Thanks for the suggestion! However, I wasn't able to locate the `DependencyUtils` file in my project. For reference, the React Native versions we’re using are:

* `"react-native": "0.79.3"`
* `"react-native": "0.74.6"`

It’s possible that the structure of the React Native Gradle plugin has changed in these versions. If you have more context on where exactly `DependencyUtils` might be located in these versions, that would be really helpful!

**Comment by Girish-GAP** [comment]
In my case (RN 0.72), I can see that it's already pointing to https://central.sonatype.com/repository/maven-snapshots/, but it's still trying to access https://oss.sonatype.org/content/repositories/snapshots, causing the build to fail.


<img width="1389" height="848" alt="Image" src="https://github.com/user-attachments/assets/5b4d4f90-a7a8-4b43-a3c4-67880f109f21" />

**Comment by vivektkclt** [comment]
Hi @yangyansong-adbe , we’re not confident in patching the core React Native plugin ourselves for a production app, especially since the `https://oss.sonatype.org/content/repositories/snapshots/` URL is coming from within the React Native plugin itself.

Is there a possibility to handle or override this issue from the Adobe plugin instead? Modifying the core React Native plugin could potentially have a broader impact on the stability of the entire app, which we'd prefer to avoid.

**Comment by Girish-GAP** [comment]
Hi @yangyansong-adbe ,

I'm also unsure whether removing this might affect other libraries or compromise the stability of the build. Would be great if this could be handled within the Adobe plugin itself.

**Comment by Girish-GAP** [comment]
@yangyansong-adbe , Thanks a lot, this solution is working well ! 🙌

Just one quick doubt, with this filtering applied, the build still resolves Adobe SDKs correctly, right? It won’t cause any issues down the line?

Also, out of curiosity, what was the original purpose of the snapshot repository?

Thanks.

**Comment by Girish-GAP** [comment]
Thanks a lot for the detailed explanation, @yangyansong-adbe  🙏
That really clarifies everything.

Thanks again for your quick support and clear guidance!
